---
steps:
  - name: ':ruby: 2.5 tests'
    plugins:
      - docker-compose#v3.7.0:
          config: .buildkite/docker/docker-compose.yml
          run: test
          args:
            RUBY_VERSION=2.5
  - name: ':ruby: 2.6 tests'
    plugins:
      - docker-compose#v3.7.0:
          config: .buildkite/docker/docker-compose.yml
          run: test
          args:
            RUBY_VERSION=2.6
