version: '3'

services:
  test:
    build:
      dockerfile: '.buildkite/docker/Dockerfile'
      context: '../../'
    command: ["bin/rake"]
  commitlint:
    build:
      dockerfile: '.buildkite/docker/commitlint.Dockerfile'
      context: '../../'
