version: '3'

services:
  test:
    build:
      dockerfile: '.buildkite/docker/Dockerfile'
      context: '../../'
    command: ["bin/rake"]
  node:
    build:
      dockerfile: '.buildkite/docker/node.Dockerfile'
      context: '../../'
    volumes:
      - ../../:/app
      - /app/node_modules
